### ISSUE TITLE
run tests error

### ISSUE THREAD

**Issue by Niushimeng** [woodemi/tencentcloud-sdk-flutter#8]
I got an error when I run then  initOralProcess test.
The apiVersion has an extra spaces in class SoeClient;.
I also got an error After I delete it. That is 
{Response: {RequestId: af0ead8d-3122-4ed0-b940-a78683f5bdb5, Error: {Code: InvalidParameterValue.RefTxtTooLang, Message: 输入文本太长。}}}

can you help me?

**Comment by Sunbreak** [comment]
@Niushimeng QQ: 251013692
